# Welcome to Serverless!

service: gaming-serverless
app: jg-streaming-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2

functions:
  streamingAPI:
    handler: Controller/products.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /streaming
          method: post
      - http:
          path: /streaming
          method: get
      - http:
          path: /streaming/{streamingId}
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
